import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from '../tailwind.config.js';

export const fullConfig = resolveConfig(tailwindConfig);

export const B64_IMAGE_HEADER: string = 'data:image/png;base64, ';

export const negativePromptTagSuggestions = [
    'abstract',
    'animal',
    'architecture',
    'art',
    'beach',
    'black and white',
    'celebrity',
    'city',
    'food',
    'landscape',
    'love',
    'macro',
    'motivational',
    'nature',
    'night',
    'blown out',
    'illustration',
    'pattern',
    'people',
    'portrait',
    'sky',
    'sport',
    'poorly Rendered face',
    'poorly drawn face',
    'poor facial details',
    'poorly drawn hands',
    'poorly rendered hands',
    'low resolution',
    'Images cut out at the top, left, right, bottom.',
    'bad composition',
    'mutated body parts',
    'blurry image',
    'disfigured',
    'oversaturated',
    'bad anatomy',
    'deformed body features',
    'out of frame',
    'lowres',
    'text',
    'error',
    'cropped',
    'worst quality',
    'low quality',
    'jpeg artifacts',
    'ugly',
    'duplicate',
    'morbid',
    'mutilated',
    'out of frame',
    'extra fingers',
    'mutated hands',
    'poorly drawn hands',
    'poorly drawn face',
    'mutation',
    'deformed',
    'blurry',
    'dehydrated',
    'bad anatomy',
    'bad proportions',
    'extra limbs',
    'cloned face',
    'disfigured',
    'gross proportions',
    'malformed limbs',
    'missing arms',
    'missing legs',
    'extra arms',
    'extra legs',
    'fused fingers',
    'too many fingers',
    'long neck',
    'username',
    'watermark',
    'signature',
];

export const enum DialogType {
    OPEN = 'open',
    SAVE = 'save',
}

export const enum BashfulAppProject {
    BASHFUL_PROJECT_FILE_EXTENSION = 'bashful',
    BASHFUL_PROJECT_FILE_NAME = 'bashful_project',
    BASHFUL_PROJECT_FILE_TYPE = 'bashful',
    BASHFUL_PHOTOSHOP_FILE_NAME = 'photoshop.psd',
    BASHFUL_STATE_FILE_NAME = 'bashful.json',
}

export const enum ContextHistoryEnum {
    HISTORY_FILE_FLAG = 'history',
    TEMP_FILE_FLAG = 'temp',
}

export const enum PhotoshopTool {
    MOVETOOL = 'moveTool',
    MARQUEERECTTOOL = 'marqueeRectTool',
    MARQUEEELLIPTOOL = 'marqueeEllipTool',
    MARQUEESINGLEROWTOOL = 'marqueeSingleRowTool',
    MARQUEESINGLECOLUMNTOOL = 'marqueeSingleColumnTool',
    LASSOTOOL = 'lassoTool',
    POLYSELTOOL = 'polySelTool',
    MAGNETICLASSOTOOL = 'magneticLassoTool',
    QUICKSELECTTOOL = 'quickSelectTool',
    MAGICWANDTOOL = 'magicWandTool',
    CROPTOOL = 'cropTool',
    SLICETOOL = 'sliceTool',
    SLICESELECTTOOL = 'sliceSelectTool',
    SPOTHEALINGBRUSHTOOL = 'spotHealingBrushTool',
    MAGICSTAMPTOOL = 'magicStampTool',
    PATCHSELECTION = 'patchSelection',
    REDEYETOOL = 'redEyeTool',
    PAINTBRUSHTOOL = 'paintbrushTool',
    PENCILTOOL = 'pencilTool',
    COLORREPLACEMENTBRUSHTOOL = 'colorReplacementBrushTool',
    CLONESTAMPTOOL = 'cloneStampTool',
    PATTERNSTAMPTOOL = 'patternStampTool',
    HISTORYBRUSHTOOL = 'historyBrushTool',
    ARTBRUSHTOOL = 'artBrushTool',
    ERASERTOOL = 'eraserTool',
    BACKGROUNDERASERTOOL = 'backgroundEraserTool',
    MAGICERASERTOOL = 'magicEraserTool',
    GRADIENTTOOL = 'gradientTool',
    BUCKETTOOL = 'bucketTool',
    BLURTOOL = 'blurTool',
    SHARPENTOOL = 'sharpenTool',
    SMUDGETOOL = 'smudgeTool',
    DODGETOOL = 'dodgeTool',
    BURNINTOOL = 'burnInTool',
    SATURATIONTOOL = 'saturationTool',
    PENTOOL = 'penTool',
    FREEFORMPENTOOL = 'freeformPenTool',
    ADDKNOTTOOL = 'addKnotTool',
    DELETEKNOTTOOL = 'deleteKnotTool',
    CONVERTKNOTTOOL = 'convertKnotTool',
    TYPECREATEOREDITTOOL = 'typeCreateOrEditTool',
    TYPEVERTICALCREATEOREDITTOOL = 'typeVerticalCreateOrEditTool',
    TYPECREATEMASKTOOL = 'typeCreateMaskTool',
    TYPEVERTICALCREATEMASKTOOL = 'typeVerticalCreateMaskTool',
    PATHCOMPONENTSELECTTOOL = 'pathComponentSelectTool',
    DIRECTSELECTTOOL = 'directSelectTool',
    RECTANGLETOOL = 'rectangleTool',
    ROUNDEDRECTANGLETOOL = 'roundedRectangleTool',
    ELLIPSETOOL = 'ellipseTool',
    POLYGONTOOL = 'polygonTool',
    LINETOOL = 'lineTool',
    CUSTOMSHAPETOOL = 'customShapeTool',
    TEXTANNOTTOOL = 'textAnnotTool',
    SOUNDANNOTTOOL = 'soundAnnotTool',
    EYEDROPPERTOOL = 'eyedropperTool',
    COLORSAMPLERTOOL = 'colorSamplerTool',
    RULERTOOL = 'rulerTool',
    HANDTOOL = 'handTool',
    ZOOMTOOL = 'zoomTool',
}
