import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from '../tailwind.config.js';

export const fullConfig = resolveConfig(tailwindConfig);

export const B64_IMAGE_HEADER: string = 'data:image/png;base64, ';

export const enum ContextHistoryEnum {
    HISTORY_FILE_FLAG = 'history',
    TEMP_FILE_FLAG = 'temp',
}

export const enum PhotoshopTool {
    MOVETOOL = 'moveTool',
    MARQUEERECTTOOL = 'marqueeRectTool',
    MARQUEEELLIPTOOL = 'marqueeEllipTool',
    MARQUEESINGLEROWTOOL = 'marqueeSingleRowTool',
    MARQUEESINGLECOLUMNTOOL = 'marqueeSingleColumnTool',
    LASSOTOOL = 'lassoTool',
    POLYSELTOOL = 'polySelTool',
    MAGNETICLASSOTOOL = 'magneticLassoTool',
    QUICKSELECTTOOL = 'quickSelectTool',
    MAGICWANDTOOL = 'magicWandTool',
    CROPTOOL = 'cropTool',
    SLICETOOL = 'sliceTool',
    SLICESELECTTOOL = 'sliceSelectTool',
    SPOTHEALINGBRUSHTOOL = 'spotHealingBrushTool',
    MAGICSTAMPTOOL = 'magicStampTool',
    PATCHSELECTION = 'patchSelection',
    REDEYETOOL = 'redEyeTool',
    PAINTBRUSHTOOL = 'paintbrushTool',
    PENCILTOOL = 'pencilTool',
    COLORREPLACEMENTBRUSHTOOL = 'colorReplacementBrushTool',
    CLONESTAMPTOOL = 'cloneStampTool',
    PATTERNSTAMPTOOL = 'patternStampTool',
    HISTORYBRUSHTOOL = 'historyBrushTool',
    ARTBRUSHTOOL = 'artBrushTool',
    ERASERTOOL = 'eraserTool',
    BACKGROUNDERASERTOOL = 'backgroundEraserTool',
    MAGICERASERTOOL = 'magicEraserTool',
    GRADIENTTOOL = 'gradientTool',
    BUCKETTOOL = 'bucketTool',
    BLURTOOL = 'blurTool',
    SHARPENTOOL = 'sharpenTool',
    SMUDGETOOL = 'smudgeTool',
    DODGETOOL = 'dodgeTool',
    BURNINTOOL = 'burnInTool',
    SATURATIONTOOL = 'saturationTool',
    PENTOOL = 'penTool',
    FREEFORMPENTOOL = 'freeformPenTool',
    ADDKNOTTOOL = 'addKnotTool',
    DELETEKNOTTOOL = 'deleteKnotTool',
    CONVERTKNOTTOOL = 'convertKnotTool',
    TYPECREATEOREDITTOOL = 'typeCreateOrEditTool',
    TYPEVERTICALCREATEOREDITTOOL = 'typeVerticalCreateOrEditTool',
    TYPECREATEMASKTOOL = 'typeCreateMaskTool',
    TYPEVERTICALCREATEMASKTOOL = 'typeVerticalCreateMaskTool',
    PATHCOMPONENTSELECTTOOL = 'pathComponentSelectTool',
    DIRECTSELECTTOOL = 'directSelectTool',
    RECTANGLETOOL = 'rectangleTool',
    ROUNDEDRECTANGLETOOL = 'roundedRectangleTool',
    ELLIPSETOOL = 'ellipseTool',
    POLYGONTOOL = 'polygonTool',
    LINETOOL = 'lineTool',
    CUSTOMSHAPETOOL = 'customShapeTool',
    TEXTANNOTTOOL = 'textAnnotTool',
    SOUNDANNOTTOOL = 'soundAnnotTool',
    EYEDROPPERTOOL = 'eyedropperTool',
    COLORSAMPLERTOOL = 'colorSamplerTool',
    RULERTOOL = 'rulerTool',
    HANDTOOL = 'handTool',
    ZOOMTOOL = 'zoomTool',
}
