export const B64_IMAGE_HEADER: string = 'data:image/png;base64, ';

export class ContextHistoryEnums {
    static HISTORY_FILE_FLAG = 'history';
}

export class PhotoshopTool {
    static MOVETOOL = 'moveTool';
    static MARQUEERECTTOOL = 'marqueeRectTool';
    static MARQUEEELLIPTOOL = 'marqueeEllipTool';
    static MARQUEESINGLEROWTOOL = 'marqueeSingleRowTool';
    static MARQUEESINGLECOLUMNTOOL = 'marqueeSingleColumnTool';
    static LASSOTOOL = 'lassoTool';
    static POLYSELTOOL = 'polySelTool';
    static MAGNETICLASSOTOOL = 'magneticLassoTool';
    static QUICKSELECTTOOL = 'quickSelectTool';
    static MAGICWANDTOOL = 'magicWandTool';
    static CROPTOOL = 'cropTool';
    static SLICETOOL = 'sliceTool';
    static SLICESELECTTOOL = 'sliceSelectTool';
    static SPOTHEALINGBRUSHTOOL = 'spotHealingBrushTool';
    static MAGICSTAMPTOOL = 'magicStampTool';
    static PATCHSELECTION = 'patchSelection';
    static REDEYETOOL = 'redEyeTool';
    static PAINTBRUSHTOOL = 'paintbrushTool';
    static PENCILTOOL = 'pencilTool';
    static COLORREPLACEMENTBRUSHTOOL = 'colorReplacementBrushTool';
    static CLONESTAMPTOOL = 'cloneStampTool';
    static PATTERNSTAMPTOOL = 'patternStampTool';
    static HISTORYBRUSHTOOL = 'historyBrushTool';
    static ARTBRUSHTOOL = 'artBrushTool';
    static ERASERTOOL = 'eraserTool';
    static BACKGROUNDERASERTOOL = 'backgroundEraserTool';
    static MAGICERASERTOOL = 'magicEraserTool';
    static GRADIENTTOOL = 'gradientTool';
    static BUCKETTOOL = 'bucketTool';
    static BLURTOOL = 'blurTool';
    static SHARPENTOOL = 'sharpenTool';
    static SMUDGETOOL = 'smudgeTool';
    static DODGETOOL = 'dodgeTool';
    static BURNINTOOL = 'burnInTool';
    static SATURATIONTOOL = 'saturationTool';
    static PENTOOL = 'penTool';
    static FREEFORMPENTOOL = 'freeformPenTool';
    static ADDKNOTTOOL = 'addKnotTool';
    static DELETEKNOTTOOL = 'deleteKnotTool';
    static CONVERTKNOTTOOL = 'convertKnotTool';
    static TYPECREATEOREDITTOOL = 'typeCreateOrEditTool';
    static TYPEVERTICALCREATEOREDITTOOL = 'typeVerticalCreateOrEditTool';
    static TYPECREATEMASKTOOL = 'typeCreateMaskTool';
    static TYPEVERTICALCREATEMASKTOOL = 'typeVerticalCreateMaskTool';
    static PATHCOMPONENTSELECTTOOL = 'pathComponentSelectTool';
    static DIRECTSELECTTOOL = 'directSelectTool';
    static RECTANGLETOOL = 'rectangleTool';
    static ROUNDEDRECTANGLETOOL = 'roundedRectangleTool';
    static ELLIPSETOOL = 'ellipseTool';
    static POLYGONTOOL = 'polygonTool';
    static LINETOOL = 'lineTool';
    static CUSTOMSHAPETOOL = 'customShapeTool';
    static TEXTANNOTTOOL = 'textAnnotTool';
    static SOUNDANNOTTOOL = 'soundAnnotTool';
    static EYEDROPPERTOOL = 'eyedropperTool';
    static COLORSAMPLERTOOL = 'colorSamplerTool';
    static RULERTOOL = 'rulerTool';
    static HANDTOOL = 'handTool';
    static ZOOMTOOL = 'zoomTool';
}
